### ISSUE TITLE
Different behaviour on devel and small nodes. CUDA not available on "small" nodes anymore. 

### ISSUE THREAD

**Issue by henzler** [jade-hpc-gpu/jade-hpc-gpu.github.io#112]
I have been using for jade over one year now and CUDA was always available by default when executing jobs using a singularity container like the following:
```
singularity exec --nv -B /raid/local_scratch/$SLURM_JOB_USER-$SLURM_JOB_ID:/local_scratch,/raid/local_scratch/$SLURM_JOB_USER-$SLURM_JOB_ID/.tmp:/tmp ./server/pytorch.img python3 -u -W ignore ./train.py
```
 As of 2 days ago, CUDA is apparently not available anymore on 'small' nodes as `nvidia-smi` returns:

```
ue Sep 24 16:59:06 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.145                Driver Version: 384.145                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M
```

When I use `devel` I still get CUDA:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.67       Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
```
shouldn't the behaviour of `devel` and `small` be the same for debugging purposes? My scripts run fine on `devel` but fail on `small`.

**Comment by f90** [comment]
Also driver versions are not the same, which doesn't help debugging your code either when it runs fine on devel but suddenly breaks when you run it on the small nodes.

**Comment by twinkarma** [comment]
Far as I know it seems the `devel` node is for testing against upcoming system changes e.g. the newer driver version. For normal running and testing of your own code, the `small` partition should be used.

The new drivers should have been rolled out to most (if not all) nodes now since you last posted and CUDA should be available with the addition of v10 so let me know if this issue persists.

**Comment by f90** [comment]
If that is the case @twinkarma I am wondering how we are supposed to test in advance whether our code will actually run on the ``small`` nodes? If we cannot use the ``devel`` nodes to quickly do that (without long queue times), we would have to submit code, wait for days in the queue for ``small`` and ``big`` nodes just to find out that the code crashed immediately due to some CUDA or other environment error, and start all over again.

**Comment by twinkarma** [comment]
@f90 Ah yes having gone back to check it on this seems devel is for just testing normal code as well. The devel node did get a new graphics driver for testing but now that it's rolled out over the cluster everything should be the same version for now. 

I will bring this issue up with the ops committee about this though as I agree that a node for users to check their code should have the same software as other nodes.
