### ISSUE TITLE
Installation of Singularity containerisation software

### ISSUE THREAD

**Issue by twinkarma** [jade-hpc-gpu/jade-hpc-gpu.github.io#17]
[Singularity](http://singularity.lbl.gov) is designed to allow for use of containers inside HPC environment. Specifically it:

* Does not require running daemon and root access.
* Integrates well with HPC schedulers and batch scripts
* The container exists as a single image file. It's easy for users to create their own image locally and upload it to JADE.

At Sheffield we've implemented it on our ShARC cluster, you can find the documentation for usage and installation here:

http://gpucomputing.shef.ac.uk/education/creating_gpu_singularity/
http://docs.hpc.shef.ac.uk/en/latest/sharc/software/apps/singularity.html

**Comment by sbutcher** [comment]
This affects QMUL users too for portability of environments and reproducible science.

**Comment by martinjhnhadley** [comment]
@twinkarma @mondus how goes the scheduling for a ML Container meeting in Oxford?

**Comment by Parker-A** [comment]
Hi
Can you upload a sample container (caffe or torch) to Jade so I can do some testing with Singularity please ? Just let me know where you upload it. 
Thanks

**Comment by twinkarma** [comment]
I've uploaded a caffe image, it's located in:

/jmain01/home/JAD009/txk03/shared/caffe-gpu.img

**Comment by twinkarma** [comment]
I'm not sure if out-of-box GPU support is working properly now for Singularity but in the links in the original post I've illustrated a way to mount Nvidia driver files so that GPUs can be used.

**Comment by Parker-A** [comment]
Got it thanks. Been able to run a container on a DGX. 
atostest@dgj223:~$ /jmain01/apps/singularity/bin/singularity shell /jmain01/apps/singularity/singularity-images/caffe-gpu.img
Singularity: Invoking an interactive shell within container...

atostest@dgj223:~$ cat /etc/issue
Ubuntu 16.04.3 LTS \n \l

atostest@dgj223:~$ exit
atostest@dgj223:~$ cat /etc/issue
Ubuntu 14.04.5 LTS \n \l

Will keep testing. Thanks!

**Comment by Parker-A** [comment]
Hmm, I can not access the GPU from inside the container:

atostest@dgj116:~$ /jmain01/apps/singularity/bin/singularity shell --nv /jmain01/apps/singularity/singularity-images/caffe-gpu.img
WARNING: Library bind directory not present in container, update container
Singularity: Invoking an interactive shell within container...

atostest@dgj116:~$ nvidia-smi
NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.

Is the NVidia driver installed with the container ? Or does it try to use the host driver ?
The"nvidia-smi" command works fine outside the container.

Could we have a mis match of drivers ? The host (Ubuntu 14) is runnign 375.66
Or is it something simple ?

**Comment by twinkarma** [comment]
You might want to try the `--nv` flag first to see if GPU support is now working out of the box.

Othewise, what we do at UoS is essentially:
1. Get nvidia driver (that matches what's installed on the cluster) and host it in a public location on the network
1. Mount the folder with driver files in to the /nvbin and /nvlib folder within the container. This is done through the singularity configuration file.

More detailed instruction below:
http://gpucomputing.shef.ac.uk/education/creating_gpu_singularity/

**Comment by Parker-A** [comment]
I tried the --nv first (see above) - didn't work.

The cuda version in your sample container is 8.0.61 - system has 8.0.44.

$ /jmain01/apps/singularity/bin/singularity shell --nv -B /usr/lib/nvidia-375:/nvlib,/usr/lib/nvidia-375/bin:/nvbin /jmain01/apps/singularity/singularity-images/caffe-gpu.img

WARNING: Library bind directory not present in container, update container
Singularity: Invoking an interactive shell within container...

atostest@dgj116:~$ export LD_LIBRARY_PATH=/nvlib
atostest@dgj116:~$ /nvbin/nvidia-smi
NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.

I'll look at it next week. You can try this out yourself if you wish - just setup a slurm session in interactive mode from the login node. (srun -I --pty -t 0-10:00 --gres gpu:1 /bin/bash)
You should have access to the singularity directory now (see path above).

**Comment by Parker-A** [comment]
Managed to get sigularity working fine. Don't need to map /nvlib or /nvlink any more with Singularity 2.3.
This is a good link for reference: https://hpc.nih.gov/apps/singularity.html#gpu

Just need to do some more testing, document it and try to make it as user friendly as possible. We have certain directories that should be mounted within the container.

**Comment by danbarnes333** [comment]
@Parker-A and @twinkarma, thanks for looking into this. Our lab is also interested in setting up containers on Jade and I'm porting them over from Docker. Are you planning to upgrade Singularity on Jade to 2.4 as I built our images with this version and they dont seem to play well with 2.3.1 on Jade?

**Comment by Parker-A** [comment]
Hi
I've install singularity 2.4 in /jmain01/apps/singularity/2.4
Within your container you must have a /usr/local/cuda directory (as the local one is mapped here).
I also recommend you have a "/workspace" - this is used to mount the local raid disks by Slurm.

There are 2 scripts - in the /jmain01/apps/singularity/2.4/bin directory.
singbatch
singinteractive

You call them with:
singinteractive CONTAINER_FILE
and
singbatch CONTAINER_FILE SCRIPT_TO_RUN

The idea being Slurm can call them:

srun -I --pty -t 0-10:00 --gres gpu:1 -p small /jmain01/apps/singularity/2.4/bin/singinteractive /jmain01/apps/singularity/singularity-images/caffe-gpu.img

Once it has been tested & documented we can setup a module file so you don't have to give the full path to the script. And perhaps some other variables ?

You must respect the CUDA_VISIBLE_DEVICES variable within the container, as you can see ALL the GPUs in the container. But Slurm has allocated you a specific one. Docker only shows you the GPUs have been allocated.

Slurm will clear out /workspace once you exit the container, so make sure you copy anything back to your home directory if you need it!
 
Let me know how you get on and any recommendations.
Adam

**Comment by danbarnes333** [comment]
Hi Adam,
Great I'll test this out now and let you know if I come across anything. One bind path I think that should be added to singinteractive  / the other scripts by default is `-B /tmp:/tmp` if you agree? As I was hitting some out of space errors which were caused by builds trying to write to tmp.
Thanks

**Comment by Parker-A** [comment]
Hi
I've modified the singularity configuration file to mount /tmp (so you don't have to).
I'm not a great fan of mounting /tmp as we don't actively clear it down (except at reboot). 
Just worry about either a user filling it up or leaving junk lying around.

Perhaps we will have to add a cron job to clear down /tmp after 7 days.
Thanks
Adam

**Comment by danbarnes333** [comment]
Thats fair enough. Would instead mounting a folder under the local raid disk (like the one to /workspace) be better so it would be cleared out by Slurm as well? 

Lets say a new folder `.tmp` is created at `/raid/local_scratch/$SLURM_JOB_USER-$SLURM_JOB_ID/.tmp` on launch of a job 

Then add the bind path `/raid/local_scratch/$SLURM_JOB_USER-$SLURM_JOB_ID/.tmp:/tmp`

**Comment by Parker-A** [comment]
I like the sound of that! I'll modify the scripts....
Thanks
Adam

**Comment by danbarnes333** [comment]
I thought I was having GPU configuration problems but It seems some jobs created by other users were not obeying the CUDA_VISIBLE_DEVICES. Otherwise it all seems to be working great. 

I am creating some internal instructions, will the singularity module be available soon or will there be more testing first? (otherwise the full path is fine).

Thanks

Below isn't relevant to this issue:
I will open a proper issue when I encounter the orphaned gpu processes / another user using the same gpu problem again as I forgot to get my whole env but incase its helpful now.
With a given session initiated as
`srun -I --pty --gres gpu:1 -p small /jmain01/apps/singularity/2.4/bin/singinteractive singularity_imgs/singularity-ori-gpu-1404-deps.img`
I was allocated  CUDA_VISIBLE_DEVICES=0 but another user had occupied GPUs 0->4 despite being on the small partition where users should only get one gpu.
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 375.66                 Driver Version: 375.66                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P100-SXM2...  Off  | 0000:06:00.0     Off |                    0 |
| N/A   47C    P0   165W / 300W |  15543MiB / 16276MiB |     69%   E. Process |
+-------------------------------+----------------------+----------------------+
|   1  Tesla P100-SXM2...  Off  | 0000:07:00.0     Off |                    0 |
| N/A   54C    P0   113W / 300W |  15543MiB / 16276MiB |     66%   E. Process |
+-------------------------------+----------------------+----------------------+
|   2  Tesla P100-SXM2...  Off  | 0000:0A:00.0     Off |                    0 |
| N/A   58C    P0   148W / 300W |  15543MiB / 16276MiB |     59%   E. Process |
+-------------------------------+----------------------+----------------------+
|   3  Tesla P100-SXM2...  Off  | 0000:0B:00.0     Off |                    0 |
| N/A   52C    P0   165W / 300W |  15543MiB / 16276MiB |     69%   E. Process |
+-------------------------------+----------------------+----------------------+
|   4  Tesla P100-SXM2...  Off  | 0000:85:00.0     Off |                    0 |
| N/A   53C    P0   254W / 300W |  15543MiB / 16276MiB |     80%   E. Process |
+-------------------------------+----------------------+----------------------+
|   5  Tesla P100-SXM2...  Off  | 0000:86:00.0     Off |                    0 |
| N/A   39C    P0    34W / 300W |      0MiB / 16276MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   6  Tesla P100-SXM2...  Off  | 0000:89:00.0     Off |                    0 |
| N/A   34C    P0    32W / 300W |      0MiB / 16276MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+
|   7  Tesla P100-SXM2...  Off  | 0000:8A:00.0     Off |                    0 |
| N/A   33C    P0    33W / 300W |      0MiB / 16276MiB |      0%   E. Process |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID  Type  Process name                               Usage      |
|=============================================================================|
|    0     63283    C   ...9/txk03/axd35-txk03/miniconda3/bin/python 15541MiB |
|    1     63308    C   ...9/txk03/axd35-txk03/miniconda3/bin/python 15541MiB |
|    2     63333    C   ...9/txk03/axd35-txk03/miniconda3/bin/python 15541MiB |
|    3     63358    C   ...9/txk03/axd35-txk03/miniconda3/bin/python 15541MiB |
|    4     63383    C   ...9/txk03/axd35-txk03/miniconda3/bin/python 15541MiB |
+-----------------------------------------------------------------------------+```

**Comment by twinkarma** [comment]
@danbarnes333 it is possible for users to manually overwrite the CUDA_VISIBLE_DEVICES since it's just an environment variable.  Is this possibly what's happening?

**Comment by Parker-A** [comment]
Hi
Yes it is possible for users to over write it or even ignore it.
This is the thing that worries me about singularity in a shared environment.
Docker has "GPU isolation" only giving the user access to the GPUS they have been allocated by Slurm.
In Docker we set "export NV_GPU=$CUDA_VISIBLE_DEVICES" before we launch the container. I believe this is a patch NVidia provided : https://github.com/NVIDIA/nvidia-docker/wiki/nvidia-docker

If Singularity had something similar that would be great.
Something to suggest to the Singularity developers ?
Adam

**Comment by sbutcher** [comment]
@danbarnes333  Singularity supports passing the CUDA_VISIBLE_DEVICES inside the container by setting the SINGULARITYENV_CUDA_VISIBLE_DEVICES variable. (see http://singularity.lbl.gov/docs-environment-metadata ). Does setting that variable make a difference for you?

**Comment by Parker-A** [comment]
That doesn't seem to work. I set:
export SINGULARITYENV_CUDA_VISIBLE_DEVICES=$CUDA_VISIBLE_DEVICES
In my script, before calling singularity, but I could still see all 8 GPUS.

The $CUDA_VISIBLE_DEVICES is set correctly inside the container, so CUDA apps *should* use it...
Adam
