### ISSUE TITLE
Docker daemon fails when trying to launch a contained app interactively

### ISSUE THREAD

**Issue by evodani** [jade-hpc-gpu/jade-hpc-gpu.github.io#22]
Trying to launch a contained application (in this case Torch) fails with the following error: 

```
srun --gres=gpu:1 --pty  /jmain01/apps/docker/torch 17.04
docker: Error response from daemon: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:258: applying cgroup configuration for process caused \\\"open /dev/cpuset/docker/cpuset.cpus: no such file or directory\\\"\"\n".
srun: error: dgj101: task 0: Exited with exit code 127
```

**Comment by twinkarma** [comment]
Same is happening for Theano containers. Something wrong with the docker daemon?

```
srun --gres=gpu:1 --pty  /jmain01/apps/docker/theano 17.04
docker: Error response from daemon: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"process_linux.go:258: applying cgroup configuration for process caused \\\"open /dev/cpuset/docker/cpuset.cpus: no such file or directory\\\"\"\n".
srun: error: dgj101: task 0: Exited with exit code 127
```

**Comment by LiamATOS** [comment]
Twin, Just seen this now, Looking into the issue now

**Comment by Parker-A** [comment]
Hi
It looks like 5 nodes are effected: dgj327, 416, 410, 324 & 104.
The /dev/cpusets/docker directory was missing. As soon as I created it, cgroups populated it.
Not sure why it was missing from just these nodes. Logs seem clear, filesystems are OK, restarted docker but it did not re-create it.

Seem to find similar issues here:
https://github.com/moby/moby/issues/9654
But the fix is not exactly clear.

Lets keep an eye on it, I will look at modifying the docker launch-script to check for the existence of /dev/cpusets/docker & if it does not exist, create it.

Adam

**Comment by Parker-A** [comment]
Hi
I've been looking into this some more & it appears the issue has not been resolved.
It looks like 8 of the nodes are experiencing this issue. I have drained them for the minute and will investigate on dgj404.
Adam

**Comment by Parker-A** [comment]
Hi
Looks like the issue has been resolved now.
cgroups was mounting the cpusets with "rw,cpuset,noprefix". The "noprefix" was removing the cpuset off the "/dev/cpuset/docker/cpuset.cpus" so it was "/dev/cpuset/docker/cpus".

There are 2 nodes still with the issue, but these have been drained & will be fixed when the current jobs finish on them.
Thanks
Adam

**Comment by martinjhnhadley** [comment]
Agreed this is all sorted at fortnightly call
