### ISSUE TITLE
Scheduler and task arrays issue

### ISSUE THREAD

**Issue by twinkarma** [jade-hpc-gpu/jade-hpc-gpu.github.io#34]
From Antonio @adlvdl :

There seems to be a problem with the scheduler and task arrays, I think. At the moment, I am waiting on a job on the small partition. From what I can see there are only around 40 jobs active in that partition, and I think I remember seeing many more running at the same time. The person in front of my in the queue submitted a task array. He has 16 jobs running, with around 9 to go. His status is Priority, rather than QOSMaxJobsPerUserLimit. My job is currently as Resources. Could it be that because he is still technically first in line, but can't run more jobs at the moment, my job need to wait until job array finishes?

**Comment by Parker-A** [comment]
Hi Twin
I'm not sure which job you are on about.
The job pending "resources" will go first, you have to wait (priority). The small partition is full at the moment (we have some drained nodes at the moment, which are being upgraded to Ubuntu 16/Cuda 9 - so not all the slots are available).
We use a fairshare scheduler as well, so it will priorities less active users.

**Comment by twinkarma** [comment]
@adlvdl Can you elaborate on the problem?

**Comment by adlvdl** [comment]
Hi,

Twin submitted the issue in my name as I didn't know about this Github repository as a way to report issues with JADE. The jobs mentioned in the opening post were running (or not running) Friday 02/02/18 but have since finished/runned. As I mentioned in the text, I thought there were less jobs running on small than should be possible based on the numner of DGX assigned to small, and hypothesized it could be because of a problem with the scheduler and job arrays. I didn't considered that some nodes might be off, and that explains the reduced number of jobs running and that mine couldn't start. Sorry for the confusion.

**Comment by twinkarma** [comment]
Thanks for clarifying that Antonio. Seems like the issue is resolved so I'm closing it.
