### ISSUE TITLE
Software request: Kaldi

### ISSUE THREAD

**Issue by Ore-an** [jade-hpc-gpu/jade-hpc-gpu.github.io#60]
I can't install Kaldi because it needs Subversion and some missing libraries. I also can't add a Docker image through singularity (I imagine this is the desired behaviour, as it reports "Configuration disallows users from running directory based containers"). Could you add the CUDA compiled version of Kaldi? https://hub.docker.com/r/georgepar/kaldi

**Comment by twinkarma** [comment]
You can build the Kaldi singularity image on your local machine then copy it to JADE and run that instead of using the image from docker directly. e.g.:

```
#On your local machine
sudo singularity build kaldigpu.img docker://georgepar/kaldi:gpu
```
Then copy the `kaldigpu.img` to JADE.

To run the container on JADE, you can then use the commands:

 `singinteractive kaldigpu.img` 

or 

`singbatch kaldigpu.img myscript.sh`
